# Generated by Django 2.2.7 on 2019-11-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('link', models.TextField(verbose_name='Link')),
                ('Description', models.URLField(verbose_name='Description')),
            ],
        ),
    ]
