# Generated by Django 2.2.7 on 2019-11-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='today_stories',
        ),
    ]
