# Generated by Django 2.2.7 on 2019-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191114_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today_stories',
            name='Description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='today_stories',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
