# Generated by Django 2.2.7 on 2019-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_latestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='editorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('Description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
