# Generated by Django 2.2.7 on 2019-11-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_buisness_international_national_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='bstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('link', models.URLField(verbose_name='Link')),
                ('Description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
