# Generated by Django 2.2.7 on 2019-11-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bstate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bstate',
            new_name='Mainstate',
        ),
    ]
