# Generated by Django 2.2.7 on 2019-11-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_m_sport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mainstate',
            new_name='sunday_magazine_top_stories',
        ),
        migrations.DeleteModel(
            name='M_sport',
        ),
        migrations.DeleteModel(
            name='Mainnational',
        ),
        migrations.DeleteModel(
            name='MBuisness',
        ),
    ]
