# Generated by Django 2.2.7 on 2019-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191120_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine_photo',
            name='link',
            field=models.URLField(default=6, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
