# Generated by Django 2.2.7 on 2019-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_magazine_photo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisetariffplan',
            name='link',
        ),
        migrations.RemoveField(
            model_name='art_culture',
            name='link',
        ),
        migrations.RemoveField(
            model_name='bollywood_buzz',
            name='link',
        ),
        migrations.RemoveField(
            model_name='book_review',
            name='link',
        ),
        migrations.RemoveField(
            model_name='buisness',
            name='link',
        ),
        migrations.RemoveField(
            model_name='career_education',
            name='link',
        ),
        migrations.RemoveField(
            model_name='column_editorial',
            name='link',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='link',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='link',
        ),
        migrations.RemoveField(
            model_name='health',
            name='link',
        ),
        migrations.RemoveField(
            model_name='heritage',
            name='link',
        ),
        migrations.RemoveField(
            model_name='international',
            name='link',
        ),
        migrations.RemoveField(
            model_name='latestnews',
            name='link',
        ),
        migrations.RemoveField(
            model_name='letter_editorial',
            name='link',
        ),
        migrations.RemoveField(
            model_name='magazine_photo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='national',
            name='link',
        ),
        migrations.RemoveField(
            model_name='opinion_editorial',
            name='link',
        ),
        migrations.RemoveField(
            model_name='otherimportantlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='link',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='link',
        ),
        migrations.RemoveField(
            model_name='science_technology',
            name='link',
        ),
        migrations.RemoveField(
            model_name='society',
            name='link',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='link',
        ),
        migrations.RemoveField(
            model_name='state',
            name='link',
        ),
        migrations.RemoveField(
            model_name='sunday_magazine_top_stories',
            name='link',
        ),
        migrations.RemoveField(
            model_name='today_stories',
            name='link',
        ),
        migrations.RemoveField(
            model_name='weeklyspecial',
            name='link',
        ),
        migrations.AddField(
            model_name='advertisetariffplan',
            name='pdf',
            field=models.FileField(default=6, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_culture',
            name='pdf',
            field=models.FileField(default=15, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bollywood_buzz',
            name='pdf',
            field=models.FileField(default=15, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_review',
            name='pdf',
            field=models.FileField(default=6, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buisness',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career_education',
            name='pdf',
            field=models.FileField(default=6, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column_editorial',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editorial',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fashion',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heritage',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='international',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestnews',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter_editorial',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='national',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion_editorial',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherimportantlink',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personality',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo_gallery',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='science_technology',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='society',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='pdf',
            field=models.FileField(default=14, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sunday_magazine_top_stories',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='today_stories',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyspecial',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdf'),
            preserve_default=False,
        ),
    ]
