# Generated by Django 2.2.7 on 2019-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20191120_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_news',
            name='pdf',
            field=models.FileField(default=3, upload_to='pdf'),
            preserve_default=False,
        ),
    ]
